### ISSUE TITLE
Application Crashes due to a bug

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#14]
Integration of [Fabric](https://fabric.io/home) in the application has led to crashes.

**Comment by vincent-paing** [comment]
Can I have the stracktrace?

**Comment by Pritom14** [comment]
Okay, but I received the stacktrace in my mail. Do you want that?

**Comment by Pritom14** [comment]
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nitsilchar.hp.passwordStorage/com.nitsilchar.hp.passwordStorage.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnCreateContextMenuListener(android.view.View$OnCreateContextMenuListener)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnCreateContextMenuListener(android.view.View$OnCreateContextMenuListener)' on a null object reference
       at android.app.Activity.registerForContextMenu(Activity.java:3523)
       at com.nitsilchar.hp.passwordStorage.MainActivity.onCreate(MainActivity.java:80)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by geoemm** [comment]
Could you give specific steps to reproduce the crash? It works on my phone although I haven't login or signup.

**Comment by Pritom14** [comment]
I guess its because if version problem because for some it works and for
some it doesn't. I have provided the stack trace, you can look into that
for more details.
